### PR TITLE
Version 1.0 BETA for Upper & Lower Busboard

### PR DESCRIPTION
**Pull request by Victorb101**
Created Boards, BOMs, pdfs, MCAD, & Gerbers

### CODE REVIEW

**Comment by Victorb101** [comment]
@aaronbeekay Please review for Version 1.0

**Comment by Victorb101** [comment]
@aaronbeekay Please review & pull, or approve for ordering

**Comment by aaronbeekay** [comment]
* "Upper board" needs labels (name + revision number)
* Looks like you made a screw terminal header in TE.lbr? It needs to be merged into Component-libraries (the symbol will need to be redrawn)
  * I would also be interested in convincing you to use the screw terminal we already stock (the 2pos one), even if you waste a pin on it. My talking point: it will be less work for you
* Same for the battery holder component – it needs to be in the right library and merged into Component-libraries

Looks good otherwise. I don't know what the battery holder looks like - could the "upper board" be reduced in size to only extend around where the copper contacts are, or is the PCB used for mechanical support?

I'll try to get on these faster in the future.

**Comment by aaronbeekay** [comment]
Oh, and your silk on "Lower board" has the same layer issue as in other boards (they are on 121/122 instead of 21/22). Do you have an odd default set up for your text tool or something? Not sure how that's possible actually.

**Comment by Victorb101** [comment]
@aaronbeekay These things are all done or we talked about them today.  Will you pull now?

**Pull request merged**
